services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    hostname: frontend
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 10s

  e2e:
    build:
      context: ./e2e
      dockerfile: Dockerfile
    # dependsをコメントアウトして常に起動できるようにする
    # depends_on:
    #   frontend:
    #     condition: service_healthy
    environment:
      - BASE_URL=http://frontend:3000
    volumes:
      - ./e2e:/app
      - /app/node_modules 
