name: E2E Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    
    steps:
      # リポジトリのコードをチェックアウト（ダウンロード）する
      # このステップがないとワークフローはリポジトリのファイルにアクセスできない
      - uses: actions/checkout@v4
      
      # DockerのBuildx機能をセットアップ
      # マルチプラットフォームイメージのビルドや高度なキャッシュ機能を有効にする
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      # docker-compose.ymlに定義されたサービスをバックグラウンドで起動
      # -dフラグはデタッチドモード（バックグラウンド実行）を意味する
      - name: Start services with Docker Compose
        run: docker compose up -d
      
      # フロントエンドサービスが完全に起動するまで待機
      # タイムアウト機能付きのポーリングループで健全性を確認
      - name: Wait for frontend to be ready
        run: |
          timeout=60
          while ! docker compose exec -T frontend wget -q --spider http://localhost:3000; do
            if [ $timeout -le 0 ]; then
              echo "Frontend service failed to start"
              exit 1
            fi
            echo "Waiting for frontend service to be ready... ($timeout seconds left)"
            timeout=$((timeout-5))
            sleep 5
          done
      
      # E2Eコンテナ内でPlaywrightテストを実行
      # -Tフラグは疑似TTYの割り当てを無効にする（CIでの実行に必要）
      - name: Run E2E tests
        run: docker compose exec -T e2e npm test
      
      # テスト結果のレポートをGitHub Actionsのアーティファクトとして保存
      # always()を使うことでテストが失敗した場合でもレポートを保存する
      - name: Upload test reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: e2e/playwright-report
          retention-days: 30 
